config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  root to: "games#index"
  resources :games, only: [:new, :create]
  resources :results, only: :index
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :nickname, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :game

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      user.nickname = "ゲスト"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:nickname])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end

  def new
  end

  def create
    
    params.require(:clickCount).permit(:clickCount).merge(user_id: current_user.id)
  end

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: :destroy

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません。'
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/create.html.erb
結果発表！

app/views/games/index.html.erb
<div class="index_body">
  <div class="main_image">
    <%= image_tag "m城と忍者.jpg", class:'ninja_img'%>
  </div>


  <div class="logo_signs">
    <h1 class="logo">殿を守れ</h1>
    <%# <div id="big"><%= audio_tag 'seisen.mp3', id:"sound"</div> %>
    <div class="operation">
      <% if user_signed_in? %>
        <ul class="signs">
          <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
        </ul>
      <% else %>
        <ul class="signs_log">
          <li class='sign_up'><%= link_to '新規登録', new_user_registration_path, class:"link_sign_up"%></li>
          <li class='login'><%= link_to 'ログイン', new_user_session_path,class:"link_login" %></li>
          <li class='guest_login'><%= link_to 'ゲストログイン', users_guest_sign_in_path,class:"link_guest_login", method: :post %></li>
        </ul>
      <% end %>
    </div>
  </div>

  <% if user_signed_in? %>
    <div class="game_start">
      <%= link_to 'ゲームSTART', new_game_path, class:"link_game_start", id:"game_start" %>
    </div>
  <% end %>
</div>

app/views/games/new.html.erb
<div class="game_over hidden" id="hidden">
  <div class="game_over_image">
    <%= image_tag "m城と月.jpg",class:'game_over_img'%>
  </div>
  <div id="result_point">総得点 0 点</div>
  <div class="back_index">
    <%= link_to 'トップへ戻る', root_path, class:"link_back_idx" %>
  </div>
  <div class="url_image">結果をつぶやく<br>
    <%= link_to image_tag( "twitterlogo.png" ,class:"twitter_img",alt:"ツイッター") ,"https://twitter.com/home?lang=ja" , target: :_blank, rel:"noopener noreferrer" %>
    <%= link_to image_tag( "instalogo.png" ,class:"insta_img",alt:"インスタ") ,"https://www.instagram.com/" , target: :_blank, rel:"noopener noreferrer" %>
  </div>
</div>

<div class="new_body" id="delete_screen">
  <div><%= audio_tag 'bakumatsubukyoku_hananoran.mp3', id:"geme_sound"%></div>
  <div><%= audio_tag 'koukaon.mp3', id:"ken_sound"%></div>
  <div><%= audio_tag 'yuruyakanakaze.mp3', id:"ending_sound"%></div>

  <div class="game_image">
    <%= image_tag "s城内（廊下）.jpg", class:'ninja_img'%>
  </div>
  <div class="game_display">
    <div class="last_time">残り<span id="last_time_s">10</span>秒</div>
    <div class="back_main">
      <%= link_to "トップへ戻る", root_path ,id:"game_retire"%>
    </div>
  </div>
  <div id="game_point">合計0点</div>

  <div class="before_start">
    <div class="before_start_image">
      <%= image_tag "襖１左.jpg", class:'fusuma_left' %>
      <%= image_tag "襖１右.jpg", class:'fusuma_right' %>
    </div> 
    <div class="push_start">
      <a class="sound_start" id="sound_start">音有りでプレイ</a>
      <a class="no_sound_start" id="no_sound_start">無音でプレイ</a>
    </div>
  </div>

  <div class="ninjas" id="ninjas">
    <div id="ninjas_a">
      <a><%= image_tag "f忍者7.png", class:"ninjas_a a_1", id:"ninja_a_1"%></a>
      <a><%= image_tag "f忍者8.png", class:"ninjas_a a_2", id:"ninja_a_2"%></a>
      <a><%= image_tag "f忍者7.png", class:"ninjas_a a_3", id:"ninja_a_3"%></a>
      <a><%= image_tag "f忍者猫1.png", class:"ninjas_a a_4", id:"ninja_a_4"%></a>
      <a><%= image_tag "f忍者8.png", class:"ninjas_a a_5", id:"ninja_a_5"%></a>
      <a><%= image_tag "f忍者8.png", class:"ninjas_a a_6", id:"ninja_a_6"%></a>
      <a><%= image_tag "f忍者7.png", class:"ninjas_a a_7", id:"ninja_a_7"%></a>
      <a><%= image_tag "f忍者8.png", class:"ninjas_a a_8", id:"ninja_a_8"%></a>
    </div>
    <div id="ninjas_b">
      <a><%= image_tag "f忍者6黄色2.png", class:"ninjas_b b_1", id:"ninja_b_1"%></a>
      <a><%= image_tag "f忍者1.png", class:"ninjas_b b_2", id:"ninja_b_2"%></a>
      <a><%= image_tag "f忍者1.png", class:"ninjas_b b_3", id:"ninja_b_3"%></a>
      <a><%= image_tag "f忍者6黄色2.png", class:"ninjas_b b_4", id:"ninja_b_4"%></a>
      <a><%= image_tag "f忍者1.png", class:"ninjas_b b_5", id:"ninja_b_5"%></a>
      <a><%= image_tag "f忍者6黄色2.png", class:"ninjas_b b_6", id:"ninja_b_6"%></a>
      <a><%= image_tag "f忍者1.png", class:"ninjas_b b_7", id:"ninja_b_7"%></a>
      <a><%= image_tag "f忍者1.png", class:"ninjas_b b_8", id:"ninja_b_8"%></a>
    </div>
    <div id="ninjas_c">
      <a><%= image_tag "fくの一2白.png", class:"ninjas_c c_1", id:"ninja_c_1"%></a>
      <a><%= image_tag "f忍者6.png", class:"ninjas_c c_2", id:"ninja_c_2"%></a>
      <a><%= image_tag "fくの一1白.png", class:"ninjas_c c_3", id:"ninja_c_3"%></a>
      <a><%= image_tag "fくの一2白.png", class:"ninjas_c c_4", id:"ninja_c_4"%></a>
      <a><%= image_tag "f忍者1.png", class:"ninjas_c c_5", id:"ninja_c_5"%></a>
      <a><%= image_tag "f忍者6.png", class:"ninjas_c c_6", id:"ninja_c_6"%></a>
      <a><%= image_tag "fくの一1白.png", class:"ninjas_c c_7", id:"ninja_c_7"%></a>
      <a><%= image_tag "f忍者1.png", class:"ninjas_c c_8", id:"ninja_c_8"%></a>
    </div>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>殿を守れ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&family=Yuji+Mai&family=Yuji+Syuku&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>